#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:54.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("rmdb() works", {

  expect_error(
    kwb.miacso:::rmdb()
    # No data quality level given. Data quality level 'qua.level' must be one of 'r' (raw), 'v' (valid) or 'c' (calibrated).
# 
  )

})

