#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:38.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("hsGetValData() works", {

  expect_error(
    kwb.miacso:::hsGetValData()
    # 
# Usage: hsGetValData(moniPoint, parName, firstDate, lastDate)
#   moniPoint: acronym of monitoring point: "STA" (Stallstr.),
# "TEG" (Tegeler Weg) or "MUE" (Muehlendamm)
#   parName:     parameter name, e.g. "AFS"
#   firstDate: first date of requested time period (mm/dd/yyyy)
#   lastDate:  last date of requested time period (mm/dd/yyyy)
# Returns a data.frame containing the validated data, directly drawn from
# the current databases.
  )

})

