#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:38.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("hsGetFpAndValRaw() works", {

  expect_error(
    kwb.miacso:::hsGetFpAndValRaw()
    # 
# Usage: hsGetFpAndValRaw(moniPoint, parNames, year, firstDate,
# lastDate)
#   moniPoint: acronym of monitoring point: "STA" (Stallstr.),
# "TEG" (Tegeler Weg) or "MUE" (Muehlendamm)
#   parNames: vector of parameter names, e.g. c("AFS", "CSB")
#   year: year of which data is requested
#   firstDate: first date of requested time period (mm/dd/yyyy)
#   lastDate: last date of requested time period (mm/dd/yyyy)
# Returns a data.frame with elements:
#   "dts":  timestamps,
#   "pars": parameter values and
#   "fps":  fingerprints
  )

})
