#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("miadir() works", {

  expect_error(
    kwb.miacso:::miadir()
    # src must be a file name with extension .mdb, .accdb, .xls, .xlsx or the name of an existing ODBC data source. Available ODBC data sources are:
#  * 
  )

})
