#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:56.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("hsUpdateMiaMdbs() works", {

  expect_error(
    kwb.miacso:::hsUpdateMiaMdbs()
    # argument "dfMdbs" is missing, with no default
  )

})

