#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:46.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("hsPlotAllDataAvailabilities() works", {

  expect_error(
    kwb.miacso:::hsPlotAllDataAvailabilities()
    # argument "moniPoints" is missing, with no default
  )

})

