#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-10-13 10:52:54.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("miamdb() works", {

  expect_error(
    kwb.miacso:::miamdb()
    # No (data) kind given. (Data) kind must be one of 'q' (water quality), 'h' (hydraulic) or 'r' (rain).
# 
  )

})

